federation_version: 2
subgraphs:
  user_service:
    routing_url: http://localhost:4001
    schema:
      subgraph_url: http://localhost:4001
  savings_service:
    routing_url: http://localhost:4002
    schema:
      subgraph_url: http://localhost:4002